﻿spring:
  application:
    name: SEdu
  main:
    lazy-initialization: false
  data:
    mongodb:
       uri: ${SPRING_DATA_MONGODB_URI}
       auto-index-creation: true
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8080
  servlet:
    context-path: /

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    url-primary: true
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
    enabled: true

logging:
  level:
    root: INFO
    com.mobiledev.SEdu: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.web: INFO

app:
  ai:
    speech:
      provider: ${AI_SPEECH_PROVIDER:AZURE}
    azure:
      key: ${AZURE_SPEECH_KEY:}
      region: ${AZURE_SPEECH_REGION:}